# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\SfBooks\:
    resource: '../Classes/*'

  Evoweb\SfBooks\Updates\PopulateAuthorSlugs:
    public: true

  Evoweb\SfBooks\Updates\PopulateBookSlugs:
    public: true

  Evoweb\SfBooks\Updates\PopulateCategorySlugs:
    public: true

  Evoweb\SfBooks\Updates\PopulateSeriesSlugs:
    public: true
